config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root  'books#mainbook'

  get 'static_pages/help'
  
    get 'static_pages/about'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'edit' => 'users#edit'
  get 'post' => 'static_pages#post'
  
  get 'book_detail' => 'books#details'
  get 'edit_book' => 'books#edit'
  get 'show_comment' =>'comments#view'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources:users
  resources :books
    resources :comments

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :books
    has_many :books, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username,  presence: true, length: { maximum: 50 },
                    uniqueness: true
    validates :password,  presence: true, length: { minimum: 6 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
has_secure_password
validates :password, presence: true, length: { minimum: 6 }

  def feed
    Book.all
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   # before_action :logged_in_user, only: [:create, :edit, :destroy]
  before_action :correct_user,   only: :destroy
  
   def create
    @book = current_user.books.build(book_params)

    if @book.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      render 'books#book'
    end
  end
  
  
  def edit
    @book = Book.find(params[:bid])
  end
  
  
  
  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:success] = "Book updated"
      redirect_to root_url
    else
      render 'edit'
    end
  end
  
  def book_params
      params.require(:book).permit(:content,:author,:price,:isbn,:name)
    end
   
   def destroy
        @book.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url     
  end
   
   def correct_user
      @book = current_user.books.find_by(id: params[:id])
      redirect_to root_url if @book.nil?
    end
   
    def mainbook
       @book=Book.all
       
    end
    
    def details
        @book=Book.find(params[:id])
        @comment = @book.comments.build(params[:bcomment])
    end
    
    
    # def comment_params
    #  params.require(:comment).permit(:bcomment)
    #end
    
    
end

#rails generate migration add_password_digest_to_users password_digest:string

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
 def create
    
    @comment = Comment.create(comment_params)
    if @comment.save
      flash[:success] = "Comment created!"
      redirect_to root_url
    else
      redirect_to root_url
    end
end

def view
    @book=Book.find(params[:id])

end

def showcomment
    @book=Book.find(params[:id])
end

    


 def comment_params
      params.require(:comment).permit(:bcomment, :book_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid user or password'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
  
  
end

#email: params[:session][:email].downcase
#<%= f.label :email %>
#<%= f.email_field :email, class: 'form-control' %>
#how to drop a column: rails g migration remove_field_name_from_table_name field_name:datatype
#<%= link_to "Logo", root_path, id: "logo" %>

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @book = current_user.books.build if logged_in?
    @feed_items = feed.paginate(page: params[:page])
  end

  def help
  end
  
  def about
  end

def post
    @book = current_user.books.build if logged_in?
    
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books.paginate(page: params[:page])
    
  end
  
  def new
        @user = User.new
  end
  
  
  def create
        @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Singed up successfully"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :firstname, :lastname)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
def full_title(page_title = '')
    base_title = "SFU Bookstore"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<li id="book-<%= book.id %>">
  <span class="content"><%= book.name %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(book.created_at) %> ago.
    
   
      <%= link_to "delete", book, method: :delete,
                                       data: { confirm: "You sure?" } %>
      <%= link_to "edit", edit_book_path(:bid=>book.id)%>
  </span>
</li>

app/views/books/details.html.erb
<p> Book name: </p><%= @book.name %>
<p> Author: </p>
 <%= @book.author %>
<p> Price: </p>
<%= @book.content %>
<p> ISBN: </p>
<%= @book.isbn %>
<p> Description: </p>
<%= @book.content %>


<br><br><br>
 <div style="width:100px; height:30px; background-color:red;">
<div>

 <%= render "comments/view" %>
  <%= render "comments/showcomment" %>

app/views/books/edit.html.erb
<% provide(:title, "Edit book") %>
<h1>Update your book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
        
          <%= f.label :price %>
      <%= f.text_field :price, class: 'form-control' %>
        
        <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>
      
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.label :isbn %>
      <%= f.text_field :isbn, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  
  </div>
</div>

app/views/books/mainbook.html.erb
<div class="center jumbotron"  style="background-color:white; margin-top:-75px;">
 
  <h1> <%= image_tag("logo.png", width: '200', height: '150', alt: 'Site Logo') %>Chalupa-Batman</h1>
<% if !logged_in? %>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>



<% @book.each do |book| %>
<% my_class_name = "box" %>
<div class="<%= my_class_name %>">
  <li style="text-align:center; padding:55px;" >
      <%= link_to book.name, book_detail_path(:id=>book.id)  %>
      <p style="color:red;">$<%= book.price %></p>
    </li>
  </div>

  
  <br><br>
    
  <% end %>
  

app/views/comments/_comment.html.erb
<li id="book-<%= comment.id %>">
  <span class="content"><%= comment.bcomment %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
    
  </span>
</li>

app/views/comments/_show.html.erb
<p>No Comments</p>

app/views/comments/_showcomment.html.erb
<h3>Comments:</h3>

<% @book.comments.each do |comment| %>
<table style="width:200px; height:30px; border: 1px solid red; ">
  <tr>
    <td><%= comment.bcomment %></td>
  </tr>
</table>


<% end %>

app/views/comments/_view.html.erb
<%= form_for(@comment) do |f| %>

 <div style="width:400px; height:30px;">
    <%= f.text_area :bcomment, placeholder: "Comment" %>
    </div>

  <br>
  <br>
  <%= f.hidden_field :book_id, :value=>@book.id %>
  
 
  <%= f.submit "Comment", class: "btn btn-primary" %>


<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Chalupa-Batman Books.com</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color:white;">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Post", post_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
        <li><%= link_to "Log in", login_path %></li>

          
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><h3 style="color:red;"><%= message %></h3></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_book_form.html.erb
<%= form_for(@book) do |f| %>

 <div style="width:400px; height:30px;">
    <%= f.text_area :name, placeholder: "Book name" %>
    </div>
  <%= render 'shared/error_messages', object: f.object %>
 
  <div style="width:400px; height:100px;">
 
    <%= f.text_area :content, placeholder: "Compose new ad..." %>
  </div>
  
  <div style="width:400px; height:30px;">
    <%= f.text_area :price, placeholder: "Price" %>
  </div>
  
   <div style="width:400px; height:30px;">
    <%= f.text_area :author, placeholder: "Author name" %>
  </div>
  
  <div style="width:400px; height:30px;">
    <%= f.text_area :isbn, placeholder: "ISBN" %>
  </div>
  
  
  <br>
  <br>
  <br>
  <br>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>

 <div style="width:400px; height:30px;">
    <%= f.text_area :bcomment, placeholder: "Comment" %>
    </div>

  <br>
  <br>
  <%= f.hidden_field :book_id, :value => :id %>
  
  <p><% @book.id %></p>
  <%= f.submit "Comment", class: "btn btn-primary" %>
  
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="books">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.username %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.books.count, "book") %></span>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<h1>Nice try</h1>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron"  style="background-color:white; margin-top:-75px;">
 
  <h1> <%= image_tag("logo.png", width: '200', height: '150', alt: 'Site Logo') %>Chalupa-Batman</h1>
<% if !logged_in? %>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>


<h3>List of posts:</h3>

<%= render 'shared/feed' %>

app/views/static_pages/post.html.erb
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <div style="width:400px; height:500px;">
        <%= render 'shared/book_form' %>
      </div>
    </aside>
  </div>
  
  

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :firstname %>
      <%= f.text_field :firstname, class: 'form-control' %>
        
        <%= f.label :lastname %>
      <%= f.text_field :lastname, class: 'form-control' %>
      
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    
    <%= f.label :firstname %>
      <%= f.text_field :firstname, class: 'form-control' %>
        
        <%= f.label :lastname %>
      <%= f.text_field :lastname, class: 'form-control' %>
    
    
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
      

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-md-8">
    <% if @user.books.any? %>
      <h3>Books (<%= @user.books.count %>)</h3>
      <ol class="books">
        <%= render @books %>
      </ol>
      <%= will_paginate @books %>
    <% end %>
  </div>